name: CI
on:
  push:
    branches:
      - main
      - lint-optimize
  pull_request:
  workflow_dispatch:
env:
  PGPASSWORD: submitty_dbuser
  PHP_USER: submitty_php
  PHP_GROUP: submitty_php
  CGI_USER: submitty_cgi
  SUBMITTY_DATA_DIR: /var/local/submitty
  SUBMITTY_INSTALL_DIR: /usr/local/submitty
  SUBMITTY_REPOSITORY: /usr/local/submitty/GIT_CHECKOUT/Submitty
  POSTGRES_HOST: localhost
  PHP_VER: 8.1
  NODE_VERSION: 20
  PYTHON_VERSION: "3.10"
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  js-unit:
    name: JavaScript Unit
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: site
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
              ${{ runner.os }}-cache-node-modules-
      - run: npm ci
      - run: npm run test
      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        with:
          files: site/tests/report/jest/clover.xml
          flags: js
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}
  php-unit:
    name: PHP Unit
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: site
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@2.33.0
        with:
          php-version: ${{ env.PHP_VER }}
          extensions: imagick
          coverage: pcov
      - name: Cache Composer
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Install Composer
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
              ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer install --prefer-dist --dev
      - name: Run php unit tests
        run: php vendor/bin/phpunit
      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        with:
          files: site/tests/report/clover.xml
          flags: php
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}
  python-unit:
    name: Python Unit
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Cache Pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ github.job }}-pip-${{ hashFiles('**/system_requirements.txt') }}
          restore-keys: |
              ${{ runner.os }}-${{ github.job }}-pip-
      - name: Install python libraries
        run: |
          python3 -m pip install -r .setup/pip/system_requirements.txt
          python3 -m pip install coverage # Testing util.
      # Submitty utils install & unit testing, must be put before auto grader
      # testing as auto grader depends on submitty utils to function.
      - name: Run python_submitty_utils python unit tests
        working-directory: python_submitty_utils
        run: |
          pip3 install .
  check-changed-files:
    name: Check Changed Files
    runs-on: ubuntu-22.04
    needs: [js-unit, php-unit, python-unit]
    outputs:
      run_ansible_lint: ${{ steps.check.outputs.run_ansible_lint }}
      run_css_lint: ${{ steps.check.outputs.run_css_lint }}
      run_js_lint: ${{ steps.check.outputs.run_js_lint }}
      run_twig_lint: ${{ steps.check.outputs.run_twig_lint }}
      run_php_lint: ${{ steps.check.outputs.run_php_lint }}
      run_python_lint: ${{ steps.check.outputs.run_python_lint }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch base branch for PR
        if: github.event_name == 'pull_request'
        run: git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
      - name: Check changed files
        id: check
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "run_ansible_lint=true" >> $GITHUB_OUTPUT
            echo "run_css_lint=true" >> $GITHUB_OUTPUT
            echo "run_js_lint=true" >> $GITHUB_OUTPUT
            echo "run_twig_lint=true" >> $GITHUB_OUTPUT
            echo "run_php_lint=true" >> $GITHUB_OUTPUT
            echo "run_python_lint=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            diff_base=${{ github.base_ref }}
          else
            diff_base=${{ github.event.before }}
          fi
          changed_ansible=$(git diff --name-only $diff_base ${{ github.sha }} | grep -E '^\.setup/ansible/' || true)
          changed_css=$(git diff --name-only $diff_base ${{ github.sha }} | grep -E '.*\.(css|scss)$' || true)
          changed_js=$(git diff --name-only $diff_base ${{ github.sha }} | grep -E '.*\.(js|jsx|ts|tsx)$' || true)
          changed_twig=$(git diff --name-only $diff_base ${{ github.sha }} | grep -E '(app|public|room_templates)/.*\.twig$' || true)
          changed_php=$(git diff --name-only $diff_base ${{ github.sha }} | grep -E '.*\.php$' || true)
          changed_python=$(git diff --name-only $diff_base ${{ github.sha }} | grep -E '.*\.py$' || true)
          [ -n "$changed_ansible" ] && echo "run_ansible_lint=true" >> $GITHUB_OUTPUT || echo "run_ansible_lint=false" >> $GITHUB_OUTPUT
          [ -n "$changed_css" ] && echo "run_css_lint=true" >> $GITHUB_OUTPUT || echo "run_css_lint=false" >> $GITHUB_OUTPUT
          [ -n "$changed_js" ] && echo "run_js_lint=true" >> $GITHUB_OUTPUT || echo "run_js_lint=false" >> $GITHUB_OUTPUT
          [ -n "$changed_twig" ] && echo "run_twig_lint=true" >> $GITHUB_OUTPUT || echo "run_twig_lint=false" >> $GITHUB_OUTPUT
          [ -n "$changed_php" ] && echo "run_php_lint=true" >> $GITHUB_OUTPUT || echo "run_php_lint=false" >> $GITHUB_OUTPUT
          [ -n "$changed_python" ] && echo "run_python_lint=true" >> $GITHUB_OUTPUT || echo "run_python_lint=false" >> $GITHUB_OUTPUT
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-22.04
    needs: [js-unit, php-unit, python-unit, check-changed-files]
    if: needs.check-changed-files.outputs.run_ansible_lint == 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: .setup/ansible
  css-lint:
    name: CSS Lint
    runs-on: ubuntu-22.04
    needs: [js-unit, php-unit, python-unit, check-changed-files]
    if: needs.check-changed-files.outputs.run_css_lint == 'true'
    defaults:
      run:
        working-directory: site
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
                ${{ runner.os }}-cache-node-modules-
      - run: npm ci
      - name: Run stylelint
        run: npm run css-stylelint
      - name: Run Prettier Format
        run: npm run prettier:fix
      - run: git diff --exit-code
  js-lint:
    name: JavaScript Lint
    runs-on: ubuntu-22.04
    needs: [js-unit, php-unit, python-unit, check-changed-files]
    if: needs.check-changed-files.outputs.run_js_lint == 'true'
    defaults:
      run:
        working-directory: site
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
                ${{ runner.os }}-cache-node-modules-
      - run: npm ci
      - name: Run eslint
        run: npm run eslint
      - name: Run npm build (tsc and esbuild)
        run: npm run build
  twig-lint:
    name: Twig Lint
    runs-on: ubuntu-22.04
    needs: [js-unit, php-unit, python-unit, check-changed-files]
    if: needs.check-changed-files.outputs.run_twig_lint == 'true'
    defaults:
      run:
        working-directory: site
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@2.33.0
        with:
          php-version: ${{ env.PHP_VER }}
      - name: Cache Composer
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Install Composer
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer install --prefer-dist --dev
      - name: Lint Twig Templates
        run: php scripts/symfony_console lint:twig --format=github app/ public/ room_templates/
  php-lint:
    name: PHP Lint
    runs-on: ubuntu-22.04
    needs: [js-unit, php-unit, python-unit, check-changed-files]
    if: needs.check-changed-files.outputs.run_php_lint == 'true'
    defaults:
      run:
        working-directory: site
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@2.33.0
        with:
          php-version: ${{ env.PHP_VER }}
      - name: Cache Composer
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Install Composer
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
              ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer install --prefer-dist --dev
      - name: Check syntax
        run: find -L . -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
      - name: Lint PHP code
        run: |
            php vendor/bin/phpcs --version
            php vendor/bin/phpcs
      - name: Static analysis
        run: |
            php vendor/bin/phpstan --version
            php vendor/bin/phpstan analyze app public/index.php socket/index.php
  python-lint:
    name: Python Lint
    runs-on: ubuntu-22.04
    needs: [js-unit, php-unit, python-unit, check-changed-files]
    if: needs.check-changed-files.outputs.run_python_lint == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Cache Pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ github.job }}-pip-${{ github.sha }}
          restore-keys: |
              ${{ runner.os }}-${{ github.job }}-pip-
      - name: Install python libraries
        run: python3 -m pip install -r .setup/pip/dev_requirements.txt
      - name: Run pre-commit
        run: pre-commit run --all-files
